### ISSUE TITLE
Head Attribute Sequence

### ISSUE THREAD

**Issue by ryansauter88** [RedKnight88/marketing-site-refactor#4]
# Head Attribute Sequence

## User Story
AS A marketing agency
I WANT a codebase that follows accessibility standards
SO THAT our own site is optimized for search engines

## Acceptance Criteria
GIVEN a webpage meets accessibility standards
WHEN I view the heading attributes
THEN they fall in sequential order

**Comment by RedKnight88** [comment]
As per commit 6, attributes all organized in sequential order.

**Comment by ryansauter88** [comment]
As per commit 6, reorganized CSS style attributes, element selectors and the universal selector come first, then class and identifier selectors after, as they appear on the webpage.
